services:
  # Database - 生产环境必需
  postgres:
    image: postgres:15-alpine
    container_name: mcp-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-mcp_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mcp-network

  # MCP Server - 核心后端服务
  mcp-server:
    container_name: mcp-server
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    volumes:
      - ../logs:/app/logs
    env_file:
      - ../.env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MCP_SKIP_AUTH=true
      - MCP_ADAPTER_TYPE=${MCP_ADAPTER_TYPE:-stdio}
      - MCP_MODE=${MCP_MODE:-stdio}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-mcp_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_SSL_MODE=${DB_SSL_MODE:-disable}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET:-default-secret}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-default-refresh-secret}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - USE_OFFICIAL_MCP_ADAPTER=${USE_OFFICIAL_MCP_ADAPTER:-true}
      - npm_config_registry=https://registry.npmmirror.com/
      - npm_config_proxy=
      - npm_config_https_proxy=
      - npm_config_fetch_retries=5
      - npm_config_fetch_retry_mintimeout=10000
      - npm_config_fetch_retry_maxtimeout=60000
      - npm_config_fetch_timeout=300000
      - DEBUG=mcp:*,playwright:*
    ports:
      - "3001:3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mcp-network
    # 添加DNS配置，确保能正确解析域名
    dns:
      - 8.8.8.8
      - 8.8.4.4
    # 增加重启策略
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  mcp-network:
    driver: bridge
    name: mcp-network 